### ISSUE TITLE
Icon Fonts don't appear after build

### ISSUE THREAD

**Issue by rteobaldo** [egoist/vuepack#111]
Hi.

I'm trying import some icon fonts but they don't load after run `dev` or `prod` mode.

This is how i'm loading fonts directly on App.vue:
```css
@font-face {
    font-family: element-icons;
    src: url('../assets/fonts/element-icons.eot?t=1472440741');
    src: url('../assets/fonts/element-icons.woff?t=1472440741') format('woff'),url('../assets/fonts/element-icons.ttf?t=1472440741') format('truetype'),url('../assets/fonts/element-icons.svg?t=1472440741#el-icon') format('svg');
    font-weight: 400;
    font-style: normal
}

@font-face {
  font-family: 'icomoon';
  src:  url('../assets/fonts/icomoon.ttf?y3vv4p') format('truetype'),
    url('../assets/fonts/icomoon.woff?y3vv4p') format('woff'),
    url('../assets/fonts/icomoon.svg?y3vv4p#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
When i save this compiles ok, but when it reloads on page:

![image](https://cloud.githubusercontent.com/assets/1500640/23115862/4c80a4d8-f726-11e6-9e9e-390b1ecdf4c4.png)

If i try change fonts path to another a not found path error raise. 
I supose then the path is right.

Is there just some thing i doing wrong?
